app/src/Entity/User/User.php
<?php
namespace App\Entity\User;

use App\Entity\TimestampableEntity;
use App\Exception\EntityValidationException;
use App\Repository\User\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Index as Index;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * User Entity
 *
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(
 *     name="`user`",
 *     indexes={
 *          @Index(name="user_status", columns={"status"})
 *     }
 * )
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"email"}, message="Пользователь с указанным E-mail адресом уже существует")
 */
class User implements UserInterface
{
    use TimestampableEntity;

    /**
     * @const string Роль "Пользователь"
     */
    public const ROLE_USER = 'ROLE_USER';

    /**
     * @const string Роль "Администратор"
     */
    public const ROLE_ADMIN = 'ROLE_ADMIN';

    /**
     * @const string Статус "Активен"
     */
    public const STATUS_ACTIVE = 'active';

    /**
     * @const string Статус "Заблокирован"
     */
    public const STATUS_BLOCKED = 'blocked';

    /**
     * @const string Статус "Удален"
     */
    public const STATUS_DELETED = 'deleted';

    /**
     * @return array Список ролей
     */
    public static array $roleList = [
        self::ROLE_USER => 'Пользователь',
        self::ROLE_ADMIN => 'Администратор',
    ];

    /**
     * @return array Список статусов
     */
    public static array $statusList = [
        self::STATUS_ACTIVE => 'Активен',
        self::STATUS_BLOCKED => 'Заблокирован',
        self::STATUS_DELETED => 'Удалён',
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(
     *     name="id",
     *     type="integer",
     *     nullable=false
     * )
     */
    private int $id;

    /**
     * @ORM\Column(
     *     type="string",
     *     length=200,
     *     nullable=false
     * )
     */
    private string $username;

    /**
     * @ORM\Column(
     *     type="string",
     *     length=20,
     *     nullable=false
     * )
     */
    private string $status = self::STATUS_ACTIVE;

    /**
     * @ORM\Column(
     *     type="string",
     *     length=200,
     *     unique=true,
     *     nullable=false
     * )
     */
    private string $email;

    /**
     * @ORM\Column(
     *     type="boolean",
     *     nullable=false
     * )
     */
    private bool $emailVerified = false;

    /**
     * @ORM\Column(
     *     type="string",
     *     length=100,
     *     unique=true,
     *     nullable=true
     * )
     */
    private ?string $emailVerifiedToken = null;

    /**
     * @ORM\Column(
     *     type="boolean",
     *     nullable=false
     * )
     */
    private bool $emailSubscribed = false;

    /**
     * @ORM\Column(
     *     type="string",
     *     length=100,
     *     unique=true,
     *     nullable=true
     * )
     */
    private ?string $emailSubscribedToken = null;

    /**
     * @ORM\Column(
     *     type="json",
     *     nullable=false
     * )
     */
    private array $roles = [];

    /**
     * @ORM\Column(
     *     type="string",
     *     nullable=false
     * )
     */
    private string $password;

    /**
     * @ORM\Column(
     *     type="string",
     *     length=100,
     *     unique=true,
     *     nullable=true
     * )
     */
    private ?string $passwordRestoreToken = null;

    /**
     * @ORM\Column(
     *     type="text",
     *     nullable=true
     * )
     */
    private ?string $about = null;

    /**
     * @ORM\OneToOne(
     *     targetEntity="App\Entity\User\UserPhoto"
     * )
     * @ORM\JoinColumn(
     *     name="photo_id",
     *     referencedColumnName="id",
     *     onDelete="CASCADE",
     *     nullable=true
     * )
     */
    private ?UserPhoto $photo = null;

    /**
     * @return int Идентификатор пользователя
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return string Имя пользователя
     */
    public function getUsername(): string
    {
        return $this->username;
    }

    /**
     * Установить имя пользователя
     *
     * @param string $username Имя пользователя
     * @return self
     */
    public function setUsername(string $username): self
    {
        $this->username = trim(strip_tags($username));

        return $this;
    }

    /**
     * @return string Статус пользователя
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * @return string Получить статус в виде текста
     */
    public function getStatusAsText(): string
    {
        return self::$statusList[$this->status] ?? $this->status;
    }

    /**
     * @return array Список возможных статусов
     */
    public static function getStatusList(): array
    {
        return array_flip(self::$statusList);
    }

    /**
     * Установить статус пользователя
     *
     * @param string $status Статус пользователя
     * @return self
     * @throws EntityValidationException
     */
    public function setStatus(string $status): self
    {
        if (!isset(self::$statusList[$status])) {
            throw new EntityValidationException("Некорректный статус для пользователя: '{$status}'");
        }

        $this->status = $status;

        return $this;
    }

    /**
     * @return string Получить e-mail пользователя
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * Установить E-mail пользователя
     *
     * @param string $email E-mail
     * @return self
     */
    public function setEmail(string $email): self
    {
        $this->email = (string) mb_strtolower($email);

        return $this;
    }

    /**
     * @return bool Пользователь подтвердил свой E-mail адрес?
     */
    public function getEmailVerified(): bool
    {
        return $this->emailVerified;
    }

    /**
     * Установить Подтвержение E-mail пользователя
     *
     * @param bool $emailVerified
     * @return self
     */
    public function setEmailVerified(bool $emailVerified): self
    {
        $this->emailVerified = $emailVerified;

        return $this;
    }

    /**
     * @return string|null Получить token подтверждения e-mail адреса
     */
    public function getEmailVerifiedToken(): ?string
    {
        return $this->emailVerifiedToken;
    }

    /**
     * Установить token подтверждения e-mail адреса
     *
     * @param string|null $emailVerifiedToken
     * @return self
     */
    public function setEmailVerifiedToken(?string $emailVerifiedToken): self
    {
        $this->emailVerifiedToken = $emailVerifiedToken;

        return $this;
    }

    /**
     * @return bool Пользователь подписан на E-mail рассылку?
     */
    public function getEmailSubscribed(): bool
    {
        return $this->emailSubscribed;
    }

    /**
     * Установить Подписку пользователя на E-mail рассылку
     *
     * @param bool $emailSubscribed
     * @return self
     */
    public function setEmailSubscribed(bool $emailSubscribed): self
    {
        $this->emailSubscribed = $emailSubscribed;

        return $this;
    }

    /**
     * @return string|null Получить token подтверждения e-mail адреса
     */
    public function getEmailSubscribedToken(): ?string
    {
        return $this->emailSubscribedToken;
    }

    /**
     * Установить token подтверждения e-mail адреса
     *
     * @param string|null $emailSubscribedToken
     * @return self
     */
    public function setEmailSubscribedToken(?string $emailSubscribedToken): self
    {
        $this->emailSubscribedToken = $emailSubscribedToken;

        return $this;
    }

    /**
     * @return array Получить список ролей пользователя
     *
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = self::ROLE_USER;

        return array_unique($roles);
    }

    /**
     * @return array Список возможных ролей
     */
    public static function getRolesList(): array
    {
        return array_flip(self::$roleList);
    }

    /**
     * Установить роли пользователя
     *
     * @param array $roles Список ролей
     * @return self
     * @throws EntityValidationException
     */
    public function setRoles(array $roles): self
    {
        array_map(function (string $role) {
            if (!isset(self::$roleList[$role])) {
                throw new EntityValidationException("Некорректная роль для пользователя: '{$role}'");
            }
        }, $roles);

        $this->roles = $roles;

        return $this;
    }

    /**
     * @return string Получить пароль пользователя
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    /**
     * Установить пароль пользователя
     *
     * @param string $password Новый пароль
     * @return self
     */
    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return string|null Получить token для восстановления пароля
     */
    public function getPasswordRestoreToken(): ?string
    {
        return $this->passwordRestoreToken;
    }

    /**
     * Установить token для восстановления пароля
     *
     * @param string|null $passwordRestoreToken
     * @return self
     */
    public function setPasswordRestoreToken(?string $passwordRestoreToken): self
    {
        $this->passwordRestoreToken = $passwordRestoreToken;

        return $this;
    }

    /**
     * @return string Получить описание
     */
    public function getAbout(): string
    {
        return (string) $this->about;
    }

    /**
     * Установить описание
     *
     * @param string|null $about Описание
     * @return self
     */

app/src/Controller/Backend/AnswerController.php
<?php
namespace App\Controller\Backend;

use App\Dto\Question\AnswerUpdateForm;
use App\Exception\AppException;
use App\Exception\ServiceException;
use App\Form\Question\AnswerSearchFormType;
use App\Form\Question\AnswerUpdateFormType;
use App\Service\Question\AnswerService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Контроллер управления ответами к вопросам
 *
 * @Route("/answer", name="answer_")
 */
class AnswerController extends AppController
{
    /**
     * @inheritdoc
     */
    protected string $csrfTokenName = 'answer';

    /**
     * @var AnswerService Question Answer Service
     */
    private AnswerService $answerService;

    /**
     * Конструктор
     *
     * @param AnswerService $answerService
     */
    public function __construct(
        AnswerService $answerService
    )
    {
        $this->answerService = $answerService;
    }

    /**
     * Листинг ответов
     *
     * @Route("/list/", name="list")
     *
     * @param Request $request
     * @return Response
     */
    public function list(Request $request): Response
    {
        $form = $this->createNamedForm('', AnswerSearchFormType::class);
        $form->submit(array_diff_key($request->query->all(), array_flip(['page'])));
        $filters = $form->isSubmitted() && $form->isValid() ? (array) $form->getData() : [];

        try {
            $page = (int) $request->get('page', 1);
            $paginator = $this->answerService->listing($form->getData(), $page);
        } catch (AppException $e) {
            $this->addFlash('error', $e->getMessage());
            $paginator = null;
        }

        return $this->render('answer/list.html.twig', [
            'filterForm' => $form->createView(),
            'filters' => $filters,
            'paginator' => $paginator,
        ]);
    }

    /**
     * Просмотр ответа
     *
     * @Route("/view/{id<[1-9]\d*>}/", name="view")
     *
     * @param int $id Идентификатор ответа
     * @return Response
     */
    public function view(int $id): Response
    {
        try {
            $answer = $this->answerService->getById($id);
        } catch (ServiceException $e) {
            throw new NotFoundHttpException($e->getMessage());
        }

        return $this->render('answer/view.html.twig', [
            'answer' => $answer,
        ]);
    }

    /**
     * Редактирование ответа
     *
     * @Route("/update/{id<[1-9]\d*>}/", name="update")
     *
     * @param Request $request
     * @param int $id Идентификатор ответа
     * @return Response
     */
    public function update(Request $request, int $id): Response
    {
        try {
            $answer = $this->answerService->getById($id);
        } catch (ServiceException $e) {
            throw new NotFoundHttpException($e->getMessage());
        }

        $formData = new AnswerUpdateForm();
        $formData->id = $id;
        $formData->text = $answer->getText();

        $form = $this->createForm(AnswerUpdateFormType::class, $formData);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $this->answerService->update($form->getData());

                $this->addFlash('success', 'Ответ успешно обновлён');

                return $this->redirectToRoute('backend_answer_view', ['id' => $answer->getId()]);
            } catch (AppException $e) {
                $this->addFlash('error', $e->getMessage());
            } catch (\Exception $e) {
                $this->addFlash('error', "Произошла ошибка. Попробуйте позже.");
            }
        }

        return $this->render('answer/update.html.twig', [
            'form' => $form->createView(),
            'answer' => $answer,
        ]);
    }

    /**
     * Удаление ответа
     *
     * @Route("/delete/{id<[1-9]\d*>}/", methods="POST", name="delete")
     *
     * @param Request $request
     * @param int $id Идентификатор ответа
     * @return Response
     */
    public function delete(Request $request, int $id): Response
    {
        $this->checkCsrfToken($request);

        try {
            $this->answerService->delete($id);

            $this->addFlash('success', 'Ответ успешно удален!');
        } catch (AppException $e) {
            $this->addFlash('error', $e->getMessage());
        } catch (\Exception $e) {
            $this->addFlash('error', "Произошла ошибка при удалении. Попробуйте позже.");
        }

        return $this->redirectToRoute('backend_answer_view', ['id' => $id]);
    }

    /**
     * Восстановление ответа
     *
     * @Route("/restore/{id<[1-9]\d*>}/", methods="POST", name="restore")
     *
     * @param Request $request
     * @param int $id Идентификатор ответа
     * @return Response
     */
    public function restore(Request $request, int $id): Response
    {
        $this->checkCsrfToken($request);

        try {
            $this->answerService->restore($id);

            $this->addFlash('success', 'Ответ успешно восстановлен!');
        } catch (AppException $e) {
            $this->addFlash('error', $e->getMessage());
        } catch (\Exception $e) {
            $this->addFlash('error', "Произошла ошибка при восстановлении. Попробуйте позже.");
        }

        return $this->redirectToRoute('backend_answer_view', ['id' => $id]);
    }
}

app/src/Controller/Backend/AppController.php
<?php
namespace App\Controller\Backend;

use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

/**
 * Базовый абстрактный контроллер для backend приложения
 */
abstract class AppController extends AbstractController
{
    /**
     * @var string CSRF Token name
     */
    protected string $csrfTokenName = 'default';

    /**
     * @inheritdoc
     */
    protected function renderView(string $view, array $parameters = []): string
    {
        return parent::renderView('backend/'.$view, $parameters);
    }

    /**
     * Создание формы с указанием имени (по аналогии с createForm)
     *
     * @param string $name Название формы
     * @param string $type Название класса формы
     * @param array $data Данные для маппинга
     * @param array $options Конфигурация
     * @return FormInterface Объект формы
     */
    protected function createNamedForm(string $name, string $type, $data = null, array $options = []): FormInterface
    {
        return $this->container->get('form.factory')->createNamed($name, $type, $data, $options);
    }

    /**
     * Проверка CSRF токена
     *
     * @param Request $request Request
     * @return void
     */
    protected function checkCsrfToken(Request $request)
    {
        if (!$this->isCsrfTokenValid($this->csrfTokenName, $request->request->get('_csrf_token'))) {
            throw new AccessDeniedException("CSRF check failed");
        }
    }
}

app/src/Controller/Backend/SiteController.php
<?php
namespace App\Controller\Backend;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

/**
 * Главный контроллер backend приложения
 */
final class SiteController extends AppController
{
    /**
     * Главная страница сайта
     *
     * @Route("/", name="index")
     */
    public function index(): Response
    {
        return $this->render('site/index.html.twig');
    }
}

templates/backend/question-category/create.html.twig
{% extends 'backend/layouts/controlbox.html.twig' %}
{% import "backend/components/tools.html.twig" as tools %}

{% block title %}Создать категорию - Категории - Панель управления{% endblock %}
{% block header %}Создать категорию{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{{ path('backend_index') }}">Главная</a></li>
    <li class="breadcrumb-item"><a href="{{ path('backend_questioncategory_list') }}">Категории</a></li>
    <li class="breadcrumb-item">Создать категорию</li>
{% endblock %}

{% block content %}
    {% include "backend/question-category/_form.html.twig" %}
{% endblock %}

templates/backend/question-category/list.html.twig
{% extends 'backend/layouts/controlbox.html.twig' %}
{% import "backend/components/tools.html.twig" as tools %}

{% block title %}Категории - Панель управления{% endblock %}
{% block header %}Категории{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{{ path('backend_index') }}">Главная</a></li>
    <li class="breadcrumb-item">Категории</li>
{% endblock %}

{% block content %}
    <div class="control-buttons">
        <a class="btn btn-primary" href="{{ path('backend_questioncategory_create') }}" title="Создать категорию">
            <i class="fas fa-plus"></i> Создать категорию
        </a>
    </div>

    {% set items = paginator.results %}
    {% if items|length > 0 %}
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Название</th>
                <th scope="col">Slug</th>
                <th scope="col">Вопросов</th>
                <th scope="col">Статус</th>
                <th scope="col">#</th>
            </tr>
            </thead>

            <tbody>
            {% for item in items %}
                <tr>
                    <th scope="row">{{ item.id }}</th>
                    <td>
                        {% if item.isActive %}
                            <a href="{{ appHost }}{{ item.href }}" target="_blank">{{ item.title }}</a>
                        {% else %}
                            {{ item.title }}
                        {% endif %}
                    </td>
                    <td>{{ item.slug }}</td>
                    <td>{{ item.totalQuestions }}</td>
                    <td>{{ tools.statusLabel(item.status, item.statusAsText) }}</td>
                    <td>
                        <a class="btn btn-success btn-sm" href="{{ path('backend_questioncategory_view', {'id': item.id}) }}" title="Просмотр">
                            <i class="fas fa-eye"></i>
                        </a>

                        {% if item.isActive %}
                            <a class="btn btn-primary btn-sm" href="{{ path('backend_questioncategory_update', {'id': item.id}) }}" title="Редактировать">
                                <i class="fas fa-edit"></i>
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {% include "backend/components/paginator.html.twig" %}
    {% else %}
        {{ tools.alert('info', "Ничего не найдено. Попробуйте изменить критерии поиска.") }}
    {% endif %}
{% endblock %}

{% block filters %}
    <div class="card" style="margin-top: 20px;">
        <div class="card-header">
            <b>Фильтры</b>
        </div>

        <div class="card-body">
            {{ form_start(filterForm) }}
            {{ form_row(filterForm.orderBy) }}

            {{ form_row(filterForm.id) }}
            {{ form_row(filterForm.status) }}
            {{ form_row(filterForm.title) }}

            <button class="btn btn-primary">Найти</button>
            {{ form_end(filterForm) }}
        </div>
    </div>
{% endblock %}

templates/backend/question-category/update.html.twig
{% extends 'backend/layouts/controlbox.html.twig' %}
{% import "backend/components/tools.html.twig" as tools %}

{% block title %}Редактирование категории '{{ category.title }}' - Категории - Панель управления{% endblock %}
{% block header %}Редактирование категории '{{ category.title }}'{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{{ path('backend_index') }}">Главная</a></li>
    <li class="breadcrumb-item"><a href="{{ path('backend_questioncategory_list') }}">Категории</a></li>
    <li class="breadcrumb-item">Редактирование категории '{{ category.title }}'</li>
{% endblock %}

{% block content %}
    {% include "backend/question-category/_form.html.twig" %}
{% endblock %}

templates/backend/question-category/view.html.twig
{% extends 'backend/layouts/controlbox.html.twig' %}
{% import "backend/components/tools.html.twig" as tools %}

{% block title %}Категория '{{ category.title }}' - Категории - Панель управления{% endblock %}
{% block header %}Категория '{{ category.title }}'{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{{ path('backend_index') }}">Главная</a></li>
    <li class="breadcrumb-item"><a href="{{ path('backend_questioncategory_list') }}">Категории</a></li>
    <li class="breadcrumb-item">Категория '{{ category.title }}'</li>
{% endblock %}

{% block content %}
    {% if category.isDeleted %}
        {{ tools.alert('danger', "Внимание! Категория удалена.") }}
    {% endif %}

    <div class="control-buttons">
        {% set csrf_token = csrf_token('question-category') %}
        {% if category.isActive %}
            <a class="btn btn-primary" href="{{ path('backend_questioncategory_update', {'id': category.id}) }}" title="Редактировать">
                <i class="fas fa-edit"></i> Редактировать
            </a>
        {% endif %}

        {% if category.isDeleted %}
            <form name="question_category_restore" method="POST" action="{{ path('backend_questioncategory_restore', {'id': category.id}) }}" style="display: inline-block;">
                <input type="hidden" name="_csrf_token" value="{{ csrf_token }}">
                <button type="submit" class="btn btn-warning" onclick="return confirm('Вы действительно хотите восстановить категорию?');"><i class="fas fa-trash-restore"></i> Восстановить</button>
            </form>
        {% else %}
            <form name="question_category_delete" method="POST" action="{{ path('backend_questioncategory_delete', {'id': category.id}) }}" style="display: inline-block;">
                <input type="hidden" name="_csrf_token" value="{{ csrf_token }}">
                <button type="submit" class="btn btn-danger" onclick="return confirm('Вы действительно хотите удалить категорию?');"><i class="fas fa-trash"></i> Удалить</button>
            </form>
        {% endif %}
    </div>

    <div class="detail-view">
        <table class="table table-striped table-bordered">
            <tbody>
            <tr>
                <th scope="row">ID</th>
                <td>{{ category.id }}</td>
            </tr>

            <tr>
                <th scope="row">Название</th>
                <td>{{ category.title }}</td>
            </tr>

            <tr>
                <th scope="row">Статус</th>
                <td>{{ tools.statusLabel(category.status, category.statusAsText) }}</td>
            </tr>

            <tr>
                <th scope="row">Slug</th>
                <td>{{ category.slug }}</td>
            </tr>

            <tr>
                <th scope="row">Href</th>
                <td>{{ category.href }}</td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}